### PR TITLE
Handle disconnections from Redis

### LINKED ISSUE #15: Manage Redis disconnections and re-connections
Hello :wave: 

We are using the library and so far is working great, but we came up with a possible scenario: If the connection with Redis is lost for whatever reason (maybe the cache goes down, or the connection pipe gets broken), then the library will try to fetch data from Redis and will get stuck forever (which is far from ideal). It would be great if the library could handle this case.

We think that this could be avoided by doing two things:

1. Change the status flag to use the `status` property of the ioredis' client.
2. Including a cache timeout, just in case.

We have some work in progress in a fork, so I will open a draft PR, but I would like to hear your thoughts on this one.

Keep up the good work with the library! :D

### PR DESCRIPTION
**Pull request by sgarcia-g**
Closes #15

### CODE REVIEW

File: lib/cache/index.js [hunk 1]
```diff
@@ -38,7 +41,22 @@ module.exports = (strapi, type = 'mem', opts = {}) => {
...
+        strapi.log.warn('[Cache] The cache is not ready');
+        return null;
+      }
+      return await Promise.race([
+        fn(...args),
+        rejectAfterTimeout(cacheTimeout)
+      ]);
+    } catch(e) {
+      if (e) {
+        strapi.log.warn('[Cache] There was an error with Redis', e);
```
Comment (patrixr) [inline lib/cache/index.js:55]:
```suggestion
        strapi.log.warn('[Cache] There was an error with the store', e);
```

In case different stores are added later : )

File: lib/index.js [hunk 2]
```diff
@@ -66,6 +67,11 @@ const Cache = (strapi) => {
         const pattern     = new RegExp(`^/${pluralize(model)}`);
         const keys        = await cache.keys();
 
+        if (!keys) {
+          warn('The request did not return any keys. Cache may be in an invalid state');
+          return next();
+        }
+
```
Comment (patrixr) [inline lib/index.js:74]: Does ioredis sometime return `null` ? 

If so it might be worth moving this error management to the redis file, seems too specific to be in the main file.

File: lib/cache/index.js [hunk 3]
```diff
@@ -15,8 +17,9 @@ module.exports = (strapi, type = 'mem', opts = {}) => {
 
   opts.max = opts.max || 500;
   opts.maxAge = opts.maxAge || 60 * 60 * 1000;
+  const { cacheTimeout = 500, ...storeOpts } = opts;
```
Comment (patrixr) [inline lib/cache/index.js:20]: I like the idea of a timeout 👍  
Could you add it to the list of options in the README ? Thanks !

**Review by patrixr — APPROVED** [review]
@sgarcia-g Thanks ! Added a few comments but it looks pretty good to me 👍 

Ideally I'd also love to add unit tests for the timeout, although it's harder than it seems. The whole testing is based around this weird hand-made mock I did of strapi. I'll try to work on that end

Make sure to modify the README with any new changes/options.
You may also bump the version in `package.json` (1.0.8), Github actions will then auto-release to npm 🚀

**Comment by derrickmehaffy** [comment]
@sgarcia-g if you change the `solves` to `fixes` in the PR desc it will auto close the related issue when the PR is merged

File: lib/cache/index.js (hunk 1 above)
Comment (sgarcia-g) [reply lib/cache/index.js]: Done! I also added the checks for the `allowLogs` flag in these

File: lib/index.js (hunk 2 above)
Comment (sgarcia-g) [reply lib/index.js]: In this case ioredis does not return `null` for the keys, so I removed these. I just added a fallback value in case there is a timeout, so it doesn't add any noise here.

**Comment by sgarcia-g** [comment]
All comments are addressed now @patrixr. I tried to work on the tests, and I think we might be okay with that Strapi mock but we need a way to mock `ioredis`. I tried to mock it but I am having issues with `sinon` (I have more experience with Jest, so it might take some time).

Do you think we can go without these tests for now and then work on those? :thinking: In the meantime I moved the test to use the memory story instead, so they don't break.

**Comment by patrixr** [comment]
I think it's fine to move forward without testing the timeout, I understand it is a bit tricky.

Thanks for contributing, I'll merge this in :)
